import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppContextProvider } from "@/context/AppContext";
import Container from "@/components/Container";
import CopyRights from "@/components/CopyRights";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import FadeIn from "@/components/FadeIn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppContextProvider>
          <div className="flex flex-col min-h-screen h-fit">
            <Header />
            <Container>
              <FadeIn>{children}</FadeIn>
              <Footer />
            </Container>
            <CopyRights />
          </div>
        </AppContextProvider>
      </body>
    </html>
  );
}
